# Generated by Django 4.1 on 2022-09-20 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=20, verbose_name='계좌명')),
                ('account_number', models.CharField(max_length=20, verbose_name='계좌번호')),
                ('invest_principal', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='투자원금')),
                ('stock_firm', models.CharField(choices=[('디셈버증권', '디셈버증권'), ('베스트투자', '베스트투자'), ('핀트투자증권', '핀트투자증권')], max_length=20, verbose_name='증권사')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AccountAsset',
        ),
        migrations.DeleteModel(
            name='AccountStock',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='TransactionHistory',
        ),
    ]
