# Generated by Django 4.1 on 2022-09-21 09:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_delete_asset'),
        ('account', '0002_account_delete_accountasset_delete_accountstock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='AccountAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(verbose_name='보유수량')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='현재가')),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='account.account')),
                ('info', models.ForeignKey(db_column='asset_info', on_delete=django.db.models.deletion.DO_NOTHING, related_name='info', to='asset.assetinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
